webtalk_init -webtalk_dir /root/Cameralink/Vivado/Cameralink.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 13 13:07:04 2014" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "i386" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "87f0kqk13ot7anv72mhnr71ev2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494.336 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "2.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1407927123000" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.2" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1407927123000"
webtalk_add_data -client sdk -key uid -value "1407927225000" -context "sdk\\\\bsp/1407927225000"
webtalk_add_data -client sdk -key hwid -value "1407927123000" -context "sdk\\\\bsp/1407927225000"
webtalk_add_data -client sdk -key os -value "device_tree" -context "sdk\\\\bsp/1407927225000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1407927225000"
webtalk_transmit -clientid 2554868760 -regid "NA" -xml /root/Cameralink/Vivado/Cameralink.sdk/webtalk/usage_statistics_ext_sdk.xml -html /root/Cameralink/Vivado/Cameralink.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /root/Cameralink/Vivado/Cameralink.sdk/webtalk/sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
