# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /root/Cameralink/Vivado/CLReceive.cache/wt [current_project]
set_property parent.project_path /root/Cameralink/Vivado/CLReceive.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /root/Cameralink/Vivado/CLReceive
  /root/Cameralink/Vivado/CLSend
} [current_project]
read_vhdl -library xil_defaultlib {
  /root/Cameralink/Vivado/CLReceive/hdl/FreqCalc.vhd
  /root/Cameralink/Vivado/CLReceive/hdl/CLReceive_S00_AXI.vhd
  /root/Cameralink/Vivado/CLReceive/hdl/CLReceive_M00_AXIS.vhd
  /root/Cameralink/Vivado/CLReceive/hdl/CLReceive.vhd
}
catch { write_hwdef -file CLReceive.hwdef }
synth_design -top CLReceive -part xc7z020clg484-1
write_checkpoint -noxdef CLReceive.dcp
catch { report_utilization -file CLReceive_utilization_synth.rpt -pb CLReceive_utilization_synth.pb }
