# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /root/Cameralink/Vivado/Cameralink.cache/wt [current_project]
set_property parent.project_path /root/Cameralink/Vivado/Cameralink.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
set_property ip_repo_paths {
  /root/Cameralink/Vivado/CLReceive
  /root/Cameralink/Vivado/CLSend
} [current_project]
add_files /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/design.bd
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_processing_system7_1_0/design_processing_system7_1_0.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1_board.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_xbar_0/design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_auto_pc_0/design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_auto_us_0/design_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_auto_us_0/design_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/ip/design_auto_pc_1/design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/design_ooc.xdc]
set_property is_locked true [get_files /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/design.bd]

read_vhdl -library xil_defaultlib /root/Cameralink/Vivado/Cameralink.srcs/sources_1/bd/design/hdl/design_wrapper.vhd
read_xdc /root/Cameralink/Vivado/Cameralink.srcs/constrs_1/new/Pins.xdc
set_property used_in_implementation false [get_files /root/Cameralink/Vivado/Cameralink.srcs/constrs_1/new/Pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_wrapper.hwdef }
synth_design -top design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_wrapper.dcp
catch { report_utilization -file design_wrapper_utilization_synth.rpt -pb design_wrapper_utilization_synth.pb }
