# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pins.xdc

# Block Designs: bd/design/design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design || ORIG_REF_NAME==design}]

# IP: bd/design/ip/design_processing_system7_1_0/design_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_processing_system7_1_0 || ORIG_REF_NAME==design_processing_system7_1_0}]

# IP: bd/design/ip/design_processing_system7_1_axi_periph_0/design_processing_system7_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_processing_system7_1_axi_periph_0 || ORIG_REF_NAME==design_processing_system7_1_axi_periph_0}]

# IP: bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proc_sys_reset_0 || ORIG_REF_NAME==design_proc_sys_reset_0}]

# IP: bd/design/ip/design_axi_mem_intercon_1_2/design_axi_mem_intercon_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_axi_mem_intercon_1_2 || ORIG_REF_NAME==design_axi_mem_intercon_1_2}]

# IP: bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_axi_dma_2_1 || ORIG_REF_NAME==design_axi_dma_2_1}]

# IP: bd/design/ip/design_CLReceive_0_0/design_CLReceive_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CLReceive_0_0 || ORIG_REF_NAME==design_CLReceive_0_0}]

# IP: bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_axis_data_fifo_1_1 || ORIG_REF_NAME==design_axis_data_fifo_1_1}]

# IP: bd/design/ip/design_xlconcat_0_0/design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_xlconcat_0_0 || ORIG_REF_NAME==design_xlconcat_0_0}]

# IP: bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proc_sys_reset_1 || ORIG_REF_NAME==design_proc_sys_reset_1}]

# IP: bd/design/ip/design_xbar_0/design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_xbar_0 || ORIG_REF_NAME==design_xbar_0}]

# IP: bd/design/ip/design_auto_pc_0/design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_auto_pc_0 || ORIG_REF_NAME==design_auto_pc_0}]

# IP: bd/design/ip/design_auto_us_0/design_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_auto_us_0 || ORIG_REF_NAME==design_auto_us_0}]

# IP: bd/design/ip/design_auto_pc_1/design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_auto_pc_1 || ORIG_REF_NAME==design_auto_pc_1}]

# XDC: bd/design/ip/design_processing_system7_1_0/design_processing_system7_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_processing_system7_1_0 || ORIG_REF_NAME==design_processing_system7_1_0}] {/inst }]/inst ]]

# XDC: bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proc_sys_reset_0 || ORIG_REF_NAME==design_proc_sys_reset_0}]

# XDC: bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proc_sys_reset_0 || ORIG_REF_NAME==design_proc_sys_reset_0}]

# XDC: bd/design/ip/design_proc_sys_reset_0/design_proc_sys_reset_0_ooc.xdc

# XDC: bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1_ooc.xdc

# XDC: bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_axi_dma_2_1 || ORIG_REF_NAME==design_axi_dma_2_1}] {/U0 }]/U0 ]]

# XDC: bd/design/ip/design_axi_dma_2_1/design_axi_dma_2_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_axi_dma_2_1 || ORIG_REF_NAME==design_axi_dma_2_1}] {/U0 }]/U0 ]]

# XDC: bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1_ooc.xdc

# XDC: bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_axis_data_fifo_1_1 || ORIG_REF_NAME==design_axis_data_fifo_1_1}] {/inst }]/inst ]]

# XDC: bd/design/ip/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1/design_axis_data_fifo_1_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_axis_data_fifo_1_1 || ORIG_REF_NAME==design_axis_data_fifo_1_1}] {/inst }]/inst ]]

# XDC: bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proc_sys_reset_1 || ORIG_REF_NAME==design_proc_sys_reset_1}]

# XDC: bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_proc_sys_reset_1 || ORIG_REF_NAME==design_proc_sys_reset_1}]

# XDC: bd/design/ip/design_proc_sys_reset_1/design_proc_sys_reset_1_ooc.xdc

# XDC: bd/design/ip/design_xbar_0/design_xbar_0_ooc.xdc

# XDC: bd/design/ip/design_auto_pc_0/design_auto_pc_0_ooc.xdc

# XDC: bd/design/ip/design_auto_us_0/design_auto_us_0_ooc.xdc

# XDC: bd/design/ip/design_auto_us_0/design_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_auto_us_0 || ORIG_REF_NAME==design_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/design/ip/design_auto_pc_1/design_auto_pc_1_ooc.xdc

# XDC: bd/design/design_ooc.xdc
